
services:
  ktbtracker-db:
    container_name: ktbtracker-db
    image: postgres
    restart: always
    ports:
      - "40132:5432"
    env_file: /tmp/ktbtracker-db.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ktbtracker-net

  ktbtracker-dbadmin:
    container_name: ktbtracker-dbadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "40180:80"
    env_file: /tmp/ktbtracker-db.env
    networks:
      - ktbtracker-net

  ktbtracker-api:
    container_name: ktbtracker-api
    image: ktbtracker-api
    build:
      context: .
    restart: always
    ports:
      - "40182:9080"
      - "40145:9443"
    env_file: /tmp/ktbtracker-db.env
    volumes:
      - /tmp/ktbtracker-1659484356633-444cd448ac34.json:/config/ktbtracker-1659484356633-444cd448ac34.json:ro
      - /etc/pki/tls/private/kingtigerblackbelt.com.key:/etc/x509/certs/tls.key:ro
      - /etc/pki/tls/certs/kingtigerblackbelt.com.bundle:/etc/x509/certs/tls.crt:ro
    depends_on:
      - ktbtracker-db
    networks:
      - ktbtracker-net

networks:
  ktbtracker-net:
    driver: bridge
