
services:
  ktbtracker-db:
    container_name: ktbtracker-db
    image: postgres
    restart: always
    ports:
      - "40132:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ktbtracker-net

  ktbtracker-dbadmin:
    container_name: ktbtracker-dbadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "40180:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - ktbtracker-net

  ktbtracker-api:
    container_name: ktbtracker-api
    image: ktbtracker-api
    build:
      context: .
    restart: always
    ports:
      - "40182:9080"
      - "40145:9443"
    environment:
      - DATABASE_HOST=ktbtracker-db
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=/config/ktbtracker-1659484356633-444cd448ac34.json
    volumes:
      - ${TEMP}/ktbtracker-1659484356633-444cd448ac34.json:/config/ktbtracker-1659484356633-444cd448ac34.json:ro
      - /etc/pki/tls/private/kingtigerblackbelt.com.key:/etc/x509/certs/tls.key:ro
      - /etc/pki/tls/certs/kingtigerblackbelt.com.bundle:/etc/x509/certs/tls.crt:ro
    depends_on:
      - ktbtracker-db
    networks:
      - ktbtracker-net

networks:
  ktbtracker-net:
    driver: bridge
